### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by kmohrf** [philippe44/mdnssd#1]
hi,

would you care to license your work under a non-copyleft license like the LGPL or any license at all for that matter? :)

thanks

**Comment by philippe44** [comment]
Hi - Most of this work is pre-existing in https://github.com/sudomesh/mdnssd-min so license is not really my choice. As far as my modifications are concerned, I'm happy to make them available under any non-contaminating license if you wish to, (a dual licensing solution)
