### ISSUE TITLE
Buffer overrun when decoding blank NAME (with fix)

### ISSUE THREAD

**Issue by adriancable** [philippe44/mdnssd#4]
(NB: I tried to create a branch/PR for this but got '403 permission denied' errors, so posting as an issue instead.)

The problem: parse_rr_name has incorrect logic, which prevents correct decode of a zero-length NAME. (Zero-length NAME is used by EDNS, e.g. OPT records which are not uncommon now)

Detail: parse_rr_name returns the length of the parsed data (i.e. what to increment the message pointer by to decode the next part of the message). Unfortunately due to a bug, a zero-length NAME (e.g. char *message = "\0") returns 2 bytes (instead of 1) as the length. As a result, the next decode operation starts 1 byte into the field, and so the rest of the message is decoded as junk (the parsed > size checks are only done between the different records, not within the records - so these do not help) and you will and can get undefined behaviour, SIGSEGVs, etc.

Fix: line 516 in mdnssd-min.c, change from

if(!did_jump) {

to

if(!did_jump && label_len) {

**Comment by philippe44** [comment]
Done - Thanks!
